1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [1]:
# import debugger
import re

# selenium
import selenium
import pandas as pd
from selenium import webdriver

# Beautiful soup
from bs4 import BeautifulSoup
import requests

# add time
import time

from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException

from selenium.webdriver.support.ui import WebDriverWait

In [4]:
# first, connect to the webdriver
driver=webdriver.Chrome(r"C:/Users/jakhar/Downloads/chromedriver_win32 (1)/chromedriver.exe")

# getting the webpage of mentioned url
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

C:\Users\jakha\AppData\Local\Temp\ipykernel_12956\1278244870.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/jakhar/Downloads/chromedriver_win32 (1)/chromedriver.exe")

In [17]:
# creating empty list for scraping the data

Rank = []
Name = []
Artist = []
Date = []
Views = []

In [18]:
from selenium.webdriver.common.by import By

In [19]:
# scraping Rank of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("-")
        
# Scraping Name of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("-")
        
# Scraping Artist of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]"):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("-")
        
# Scraping Upload_Date of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]"):
        Date.append(i.text)
except NoSuchElementException:
    Date.append("-")
        
# Scraping Views of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("-")
        
# creating DataFrame for scraped data
Wiki = pd.DataFrame({})
Wiki['Rank'] = Rank
Wiki['Name'] = Name
Wiki['Artist'] = Artist
Wiki['Upload Date'] = Date
Wiki['Views (in Billions)'] = Views

# removing stray numbers from Name column
Wiki.Name = Wiki.Name.apply(lambda x:x[:-4].strip('"'))
Wiki

,Rank,Name,Artist,Upload Date,Views (in Billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.85
1,2.,Despacito,Luis Fonsi,"January 12, 2017",8.16
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.70
3,4.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",6.20
4,5.,Shape of You,Ed Sheeran,"January 30, 2017",6.00
5,6.,See You Again,Wiz Khalifa,"April 6, 2015",5.89
6,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",5.30
7,8.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",5.24
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.92
9,10.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.89
10,11.,Gangnam Style,Psy,"July 15, 2012",4.80
11,12.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.55
12,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",4.35
13,14.,Axel F,Crazy Frog,"June 16, 2009",3.91
14,15.,Sugar,Maroon 5,"January 14, 2015",3.87
15,16.,Roar,Katy Perry,"September 5, 2013",3.80
16,17.,Counting Stars,OneRepublic,"May 31, 2013",3.79
17,18.,Sorry,Justin Bieber,"October 22, 2015",3.66
18,19.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.64
19,20.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.60
20,21.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.59
21,22.,Dark Horse,Katy Perry,"February 20, 2014",3.52
22,23.,Lakdi Ki Kathi,Jingle Toons,"June 14, 2018",3.48
23,24.,Faded,Alan Walker,"December 3, 2015",3.45
24,25.,Perfect,Ed Sheeran,"November 9, 2017",3.45
25,26.,Let Her Go,Passenger,"July 25, 2012",3.44
26,27.,Girls Like You,Maroon 5,"May 31, 2018",3.42
27,28.,Humpty the train on a fruits ride,Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.41
28,29.,Lean On,Major Lazer,"March 22, 2015",3.38
29,30.,Bailando,Enrique Iglesias,"April 11, 2014",3.38

In [20]:
print(len(Rank),
len(Name),
len(Artist),
len(Date),
len(Views))

30 30 30 30 30

In [21]:
driver.close()

2. Scrape the details teamIndia’sinternationalfixtures from bcci.tv. 
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1stODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [6]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
import time
from selenium.common.exceptions import NoSuchElementException

In [ ]:
# connecting to the webdriver
driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

# getting the webpage of mentioned url
url=('https://www.bcci.tv/')
driver.get(url)

In [ ]:
designation=driver.find_element(By.CLASS_NAME,"")
designation

In [9]:

nxt_button=driver.find_elements(By.XPATH,"//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
driver.get(nxt_button.get_attribute("href"))
time.sleep(3)

# creating empty lists for scraping the data
Match_Title = []
Series = []
Place = []
Date = []
Time = []

AttributeError: 'list' object has no attribute 'get_attribute'

In [ ]:
search=driver.find_element(By.CLASS_NAME,"top-bar-container")
search.click()

In [14]:
# creating empty lists for scraping the data
Match_Title = []
Series = []
Place = []
Date = []
Time = []

In [15]:
for i in driver.find_elements(By.XPATH,"//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__format']"):
    Match_Title.append(i.text)
    
for i in driver.find_elements(By.XPATH,"//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__tournament-label u-truncated']"):
    Series.append(i.text)
    
for i in driver.find_elements(By.XPATH,"//div[@class='fixture__description u-unskewed-text']/p/span"):
    Place.append(i.text)
        
for i in driver.find_elements(By.XPATH,"//span[@class='fixture__datetime tablet-only']/strong[1]"):
    Date.append(i.text.replace('\n',' '))

date=[i.split(' ',3)[:3] for i in Date]
date=[' '.join(i) for i in date]
Time=[i.split(' ',3)[-1] for i in Date]

# creating data frame
fixture=pd.DataFrame({'Match Title': Match_Title,
                          "Series": Series,
                          "Place": Place,
                          "Date": date,
                          "Time": Time})
fixture

Empty DataFrame
Columns: [Match Title, Series, Place, Date, Time]
Index: []

3. Scrape the details of State-wise GDP ofIndia fromstatisticstime.com. 
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [16]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://statisticstimes.com/")
driver.get(url)

In [17]:
# clicking on Economy button
driver.find_elements(By.XPATH,"//div[@class='navbar']/div[2]/button")

# clicking on India
driver.find_elements(By.XPATH,"//div[@class='dropdown-content']/a[3]")
time.sleep(3)

# clicking on GDP of Indian Economy
GDP = driver.find_elements(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
time.sleep(3)

In [18]:
# creating empty list
Rank = []
State = []
GSDP1 = []
GSDP2 = []
Share = []
GDP_billion = []

# scraping Rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# scraping State
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
    
# scraping GSDP at current price (19-20)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException:
    GSDP1.append("_")
    
# scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
    
# scraping Share (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
    
# scraping GDP $ billion
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append("_")
    
    
# creating DataFrame from the scraped data
GDP = pd.DataFrame({})
GDP['Rank'] = Rank
GDP['State'] = State
GDP['GSDP at current price (19-20)'] = GSDP1
GDP['GSDP at current price (18-19)'] = GSDP2
GDP['Share (18-19)'] = Share
GDP['GDP($ billion)'] = GDP_billion
GDP

Empty DataFrame
Columns: [Rank, State, GSDP at current price (19-20), GSDP at current price (18-19), Share (18-19), GDP($ billion)]
Index: []

4. Scrape the details of trending repositories on Github.com. 
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [55]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://github.com/")
driver.get(url)

C:\Users\jakha\AppData\Local\Temp\ipykernel_12956\1522202867.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

In [58]:
# getting explore button and clicking on it
explore = driver.find_elements(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details")

# selecting trending option
trend_url = driver.find_elements(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

AttributeError: 'list' object has no attribute 'get_attribute'

5. Scrape the details of top 100 songs on billiboard.com. 
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [19]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://www.billboard.com/")
driver.get(url)

In [20]:
# clicking on option button
charts=driver.find_elements(By.XPATH,"//a[@class='header__main-link header__main-link--charts']")

In [22]:
# creating empty lists
Song_Name = []
Artist_Name =[]
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

# getting urls for top 100 songs
urls = driver.find_elements(By.XPATH,"//li[@class='header__submenu__list__element']//a")
page_url = urls.get_attribute ("href")
driver.get(page_url)
time.sleep(4)

# scraping data of song names
for i in driver.find_elements(By.XPATH,"//span[@class='chart-element__information__song text--truncate color--primary']"):
    Song_Name.append(i.text)
    
# scraping data of artist names
for i in driver.find_elements(By.XPATH,"//span[@class='chart-element__information__artist text--truncate color--secondary']"):
    Artist_Name.append(i.text)
    
# scraping data of last week ranks
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--last']"):
    Last_week_rank.append(i.text)
    

# scraping data of peak ranks
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--peak']"):
    Peak_rank.append(i.text)       
    
    
# scraping data of weeks on board
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--week']"):
    Weeks_on_board.append(i.text)
    
    
# creating dataframe for scraped data
billiboard = pd.DataFrame({})
billiboard['Name'] = Song_Name
billiboard['Artist'] = Artist_Name
billiboard['Last Week Rank'] = Last_week_rank
billiboard['Peak Rank'] = Peak_rank
billiboard['Weeks on board'] = Weeks_on_board
billiboard

AttributeError: 'list' object has no attribute 'get_attribute'

6. Scrape the details of Highest sellingnovels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [68]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/")
driver.get(url)
time.sleep(3)

C:\Users\jakha\AppData\Local\Temp\ipykernel_12956\3343049671.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

In [71]:
# creating empty lists
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []


# scraping book names data
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[2]"):
    Book_name.append(i.text)

    
# scraping author names data
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author_name.append(i.text)
    except NoSuchElementException:
        Author_name.append('-')
time.sleep(3)


# scraping data of volumes sold
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[4]"):
    Volumes_sold.append(i.text)
    
    
# scraping data of publisher names
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[5]"):
    Publisher.append(i.text)
    
    
# scraping  data of genre
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[6]"):
    Genre.append(i.text)    
    
    
# creating dataframe for scraped data
Novels = pd.DataFrame({})
Novels['Book Name'] = Book_name
Novels['Author'] = Author_name
Novels['Volume sold'] = Volumes_sold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [72]:
driver.close()

7. Scrape the details most watched tv series of all time from imdb.com. 
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [77]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://www.imdb.com/list/ls095964455/")
driver.get(url)

C:\Users\jakha\AppData\Local\Temp\ipykernel_12956\380918905.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/HP/Downloads/chromedriver_win32 (1)/chromedriver.exe")

In [78]:
# creating empty lists
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

# scraped data of Names
for i in driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
    
    
# scraped data of Year span
for i in driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
    
    
# scraped data of Genre
for i in driver.find_elements(By.XPATH,"//span[@class='genre']"):
    Genre.append(i.text)
    
    
# scraped data of Run time
for i in driver.find_elements(By.XPATH,"//span[@class='runtime']"):
    Run_time.append(i.text)
    
    
# scraped data of Ratings
for i in driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
    
# scraped data of Votes
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text) 
    
    
# creating dataframe for scraped data
TV_Series = pd.DataFrame({})
TV_Series['Name'] = Name
TV_Series['Year Span'] = Year_span
TV_Series['Genre'] = Genre
TV_Series['Run Time'] = Run_time
TV_Series['Ratings'] = Ratings
TV_Series['Votes'] = Votes
TV_Series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,162,243"
1,Stranger Things,(2016–2022),"Drama, Fantasy, Horror",51 min,8.7,"1,242,403"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,027,220"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"302,176"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"261,282"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"51,670"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"63,708"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"207,656"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"43,208"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"258,169"

In [79]:
driver.close()

8. Details of Datasetsfrom UCI machine learning repositories. 
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [1]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\jakha\appdata\roaming\python\python39\site-packages (4.9.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from selenium) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from selenium) (0.10.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: outcome in c:\users\jakha\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.1)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import selenium 
import pandas as pd 
from selenium import webdriver 
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [3]:
driver = webdriver.Chrome("C:\Webb Driver\chromedriver.exe")

In [4]:
#Opening the archive page on automted chrome browser
driver.get(" https://archive.ics.uci.edu/")

In [11]:
# fetching view all dataset button from the webpage
viewall_dataset = driver.find_elements(By.XPATH,"//tbody[1]//tr/td[2]/span[2]/a")
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)
time.sleep(3)

AttributeError: 'list' object has no attribute 'get_attribute'

In [12]:
# fetching page urls of all datasets
view_list = driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")
list_url = view_list.get_attribute("href")
driver.get(list_url)
time.sleep(3)

AttributeError: 'list' object has no attribute 'get_attribute'

In [13]:
# fetching urls for each dataset
dataset_url = driver.find_elements(By.XPATH,"//p[@class='normal']//b/a")

urls = []
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [14]:
# creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

for i in urls:
    driver.get(i)
    time.sleep(3)
    
    
    # scraping  Dataset name
    try:
        dataset_name = driver.find_elements(By.XPATH,"//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    time.sleep(3)
    
    
    
    # scraping data type
    try:
        data_type = driver.find_elements(By.XPATH,"//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    time.sleep(3)
    
    
    # scraping Task
    try:
        task = driver.find_elements(By.XPATH,"//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    time.sleep(3)
    
    
    
    # scraping Attribute type
    try:
        attribute_type = driver.find_elements(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    time.sleep(3)
    
    
    
    # scraping No of Instances
    try:
        instances = driver.find_elements(By.XPATH,"//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    time.sleep(3)
    
    
    
    # scraping No of Arrtibutes
    try:
        attribute = driver.find_elements(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    time.sleep(3)
    
    
    # scraping Year
    try:
        year = driver.find_elements(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    time.sleep(3)

In [17]:
# creating dataframe for scraped data
ML = pd.DataFrame({})
ML['Data Name'] = Dataset_name 
ML['Data Type '] = Data_type
ML['Task '] = Task 
ML['Attribute Type '] = Attribute_type 
ML['No of Instance '] = No_of_instances
ML['No of Attributes '] = No_of_attributes 
ML['Year '] = Year 
ML

Empty DataFrame
Columns: [Data Name, Data Type , Task , Attribute Type , No of Instance , No of Attributes , Year ]
Index: []

9. Scrape the details of Data science recruiters Url = https://www.naukri.com/hr-recruiters-consultants
You have to find the following details: 
A) Name
B) Designation
C)Company 
D)Skills they hire for 
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and 
click on search. All this should be done through code.

In [23]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\jakha\appdata\roaming\python\python39\site-packages (4.9.0)
Requirement already satisfied: trio~=0.17 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from selenium) (0.22.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from selenium) (0.10.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.1)
Requirement already satisfied: async-generator>=1.9 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\jakha\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\jakha\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [24]:
import selenium 
import pandas as pd 
from selenium import webdriver 
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [25]:
driver = webdriver.Chrome("C:\Webb Driver\chromedriver.exe")

In [26]:
#Opening the naukri page on automted chrome browser
driver.get("https://www.naukri.com/")

In [27]:
#entering designation and location as required in the question-

designation=driver.find_element(By.CLASS_NAME,"suggestor-input ") 
designation.send_keys( 'Data Scientist')

In [28]:
location=driver.find_element(By.XPATH,"/html/body/div[1]/div[7]/div/div/div[5]/div/div/div[1]/div[1]/div/input")
location.send_keys('Banglore')

In [29]:
search=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search.click()

In [30]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

In [31]:
# scraping job title from the given page
title_tags=driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)
    
# scraping job location from the given page
location_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft locWdth"]')
for i in location_tags[0:10]:
    location=i.text
    job_location.append(location)
    
# scraping campany name from the given page
company_tags=driver.find_elements(By.XPATH,"//a[@class='subTitle ellipsis fleft']")
for i in company_tags[0:10]:
    company=i.text
    company_name.append(company)
    
# scraping job Experience from the given page
experience_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft expwdth"]')
for i in experience_tags[0:10]:
    exp=i.text
    experience_required.append(exp)

In [32]:
print(len(job_title),len(job_location),len(company_name),len(experience_required))

10 10 10 10

In [33]:
import pandas as pd
df=pd.DataFrame({'Title':job_title,'Location':job_location,'Company_name':company_name,'Experience':experience_required})
df

,Title,Location,Company_name,Experience
0,Permanent Opportunity - Data Scientist(Snaplog...,"Hybrid - Kolkata, Hyderabad/Secunderabad, Pune...",Deloitte,9-14 Yrs
1,Analystics & Modeling Specialist,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",Accenture,6-8 Yrs
2,Director/Senior Director - Data Science,"Noida, Hyderabad/Secunderabad, Pune, Gurgaon/G...",Axtria India,10-15 Yrs
3,Manager/Senior Manager - Data Science,"Noida, Hyderabad/Secunderabad, Pune, Gurgaon/G...",Axtria India,8-12 Yrs
4,Data Scientist,"Hyderabad/Secunderabad, Chennai, Bangalore/Ben...",Cognizant,4-9 Yrs
5,Data Scientist_NLP,"Mumbai, Pune, Chennai, Gurgaon/Gurugram, Banga...",Fractal Analytics,5-11 Yrs
6,Machine Learning (AI) Architect,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Persistent,5-12 Yrs
7,Data Scientist,"Hybrid - Pune, Bangalore/Bengaluru, Delhi / NC...",Infogain,3-6 Yrs
8,Senior Data Scientist,"Indore, Madhya Pradesh, Pune, Bangalore/Bengal...",Impetus Technologies,4-8 Yrs
9,Data Scientist,Bangalore/Bengaluru,Quality Engineering Software Technologies Pvt....,3-6 Yrs